apiVersion: v1
data:
  config.yaml: |
    MongoDB\Client:
      arguments:
        uri: "{ENV(TUBEE_MONGODB_URI,mongodb://localhost:27017)}"
    MongoDB\Database:
      use: '{MongoDB\Client}'
      calls:
        - method: selectDatabase
          select: true
          arguments:
            databaseName: 'tubee'
    Tubee\Async\Mail:
      arguments:
        config:
          sender_address: "no-reply@localhost"
          sender_name: "tubee"
    TaskScheduler\Scheduler:
      arguments:
        config:
          job_queue_size: 1000000
          event_queue_size: 5000000
    TaskScheduler\WorkerManager:
      arguments:
        config:
          pm: dynamic
          max_children: 4
          min_children: 2
    Zend\Mail\Transport\SmtpOptions:
      arguments:
        options:
          host: '{ENV(TUBEE_SMTP_HOST,127.0.0.1)}'
          port: 25
    Zend\Mail\Transport\TransportInterface:
      use: "Zend\\Mail\\Transport\\Smtp"
    ParagonIE\Halite\Symmetric\EncryptionKey:
      services:
        ParagonIE\HiddenString\HiddenString:
          arguments:
            value: "{ENV(ENTUBEE_ENCRYPTION_KEY,314004004fde30cdb0eb624c53eb681e78995b528f7a110f49eb4e5dcdfa2af1412c3d4e7aff5cdb68c821d14704cbb608210a9b6d1ca5077809055c3ff83be0fddb2b4ebb7f3ed3a45459aa2af2a8ca9e809821c809aa20b949dfb04c01452e4954e3c8)}"
    Psr\Log\LoggerInterface:
      use: "Monolog\\Logger"
      arguments:
        name: default
      calls:
        stderr:
          method: pushHandler
          arguments:
            handler: '{stderr}'
        stdout:
          method: pushHandler
          arguments:
            handler: '{stdout}'
      services:
        Monolog\Formatter\FormatterInterface:
          use: Monolog\Formatter\LineFormatter
          arguments:
            dateFormat: "Y-d-m H:i:s"
            format: "%datetime% [%context.category%,%level_name%]: %message% %context.params% %context.exception%\n"
          calls:
            - method: includeStacktraces
        stderr:
          use: Monolog\Handler\StreamHandler
          arguments:
            stream: 'php://stderr'
            level: 600
          calls:
            formatter:
              method: setFormatter
        stdout:
          use: Monolog\Handler\FilterHandler
          arguments:
            handler: '{output}'
            minLevelOrList: 100
            maxLevel: 550
          services:
            output:
              use: Monolog\Handler\StreamHandler
              arguments:
                stream: 'php://stdout'
                level: 100
              calls:
                formatter:
                  method: setFormatter
    Micro\Auth\Auth:
      calls:
        basic_db:
          method: injectAdapter
          arguments:
            adapter: '{basic_db}'
        ldap:
          method: injectAdapter
          arguments:
            adapter: '{ldap}'
      services:
        basic_db:
          use: "Tubee\\User\\AuthAdapter"
        oidc:
          use: "Micro\\Auth\\Adapter\\Oidc"
          arguments:
            config:
              provider_url: "https://openidconnect.example.net"
        ldap:
          use: "Micro\\Auth\\Adapter\\Basic\\Ldap"
          arguments:
            ldap_options:
              uri: "ldap://ldap-master001.gyselroth.net:389"
              basedn: "dc=gyselroth,dc=net"
              binddn: "uid=raffael.sahli,ou=it,ou=users,dc=gyselroth,dc=net"
              bindpw: Admin-rs-1@IhRSuw
              tls: true
              options:
                LDAP_OPT_PROTOCOL_VERSION: 3
kind: ConfigMap
metadata:
  creationTimestamp: null
  namespace: tubee
  name: tubee-config
