language: php
php:
- 7.2
sudo: required
os: linux
arch:
  - arm64
cache:
  directories:
  - vendor
addons:
  apt:
    packages:
    - imagemagick
    - libmagickwand-dev
    - unixodbc-dev
before_install:
- echo "extension = apcu.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- echo "\n" | pecl install imagick
- echo "\n" | pecl install sqlsrv-5.8.1
- export version=$TRAVIS_TAG
- if [[ "${version:0:1}" == "v" ]]; then version=${version:1}; fi;
- if [ "$version" == "" ]; then version=$TRAVIS_BUILD_NUMBER; fi;
script:
- make VERSION=$version
- if [ "$TRAVIS_TAG" != "" ]; then docker build -t gyselroth/tubee:$version .; fi
notifications:
  email: false
before_deploy:
- if [[ "$version" == *"-"* ]]; then export docker_tag=latest-unstable; else export docker_tag=latest; fi;
deploy:
- provider: releases
  api_key:
    secure: ZerLJK+J4TPeadfiw/La/U8+LpX/MQMu0LNOedDXN11jH96BKpeU16eeIpjfFtycMA4DSdESSqYSSmOnHw8tYmB7ONLByWX3XPzF873PHTqjo5Nu+AgkM4FE+Cn7b6f5EoBJ4tEbuf/kd55OfmVDW0/U9hVOJnJ60c+50uGk64mhLQEiJxh1jWEqHndKo/P58lsfYbzZeYhfzFiTa/TQaTydHL4ZvpIasVljnMDG/omBU+O4XGK5k9pHC5vzRi3bj/QN9qkMGflpE/yswCy6Xi8T5ZCVRvOOlzQZFpKIrvP4EGphHYseewPobTVxXNoekR2aEuariJ90gt7qg0zbbXBahNXXiPWFFDufdcbq8qn9cH9SslzuME1Z454bW+H736/prpGP8rRiYzWuZM7NSwV2+DTqDuPvz6S9iSHoIAexFlq5JavPHc54OWhDyDm8YkLRvPaYojskWps0F7Zjxff9OK4iyDnPs6gcQgypBYyoPjEtOCsElQrPkthSqFUF/eXi+9Q7+SiEJHmJpaOTefh3Ln+/W2j3viR0Dd+olkNCbe4TYJwZaP5xTy17B5bhjE6A91uUdo/CfE4D54SV84nkkhkrVc+RmNKE4aZWiagv546gHd90/uyZi/pDZ9Vj8DqXPtr/yeVX/7v467Tk/xAdfhTGRT9rB8qyISq6NSk=
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- test "$TRAVIS_TAG" != "" && version=${TRAVIS_TAG:1};
- test "$TRAVIS_TAG" != "" && docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- test "$TRAVIS_TAG" != "" && docker tag gyselroth/tubee:$version gyselroth/tubee:$docker_tag
- test "$TRAVIS_TAG" != "" && docker push gyselroth/tubee:$version
- test "$TRAVIS_TAG" != "" && docker push gyselroth/tubee:$docker_tag
- ! 'if [ "$TRAVIS_TAG" != "" ]; then curl -s -X POST -H ''Content-Type: application/json''
  -H ''Accept: application/json'' -H ''Travis-API-Version: 3'' -H "Authorization:
  token $TRAVIS_API_TOKEN" -d ''{"request":{"message":"trigger build", "branch":"master"}}''
  "https://api.travis-ci.com/repo/gyselroth%2Ftubee-sdk-typescript-node/requests"; fi'
env:
  global:
    secure: lGrT8095L0RrzH7EuGAtc++qYG9CJlVAyj1mdaPAtOg34FmZkrEAgJ1RFtucj4FvtQhxFwQFbqnMIIhh7i0aHysaWVbYa5mnKxVdC5Z64KsQ8z/nwlm9o2uKUqbn18kjDui/aKLd5NLIpmkh56O+PrLgGAZHb2YwmPHosWjHcyN3yNKpXiwV+NRiLqWl6OhQ8Y47FUXX3o8WsJMMY+4MNvmuEtia5OE3l+1ioybYRobF3TYRiDIYSmBzafyAUK9NiUscbtR3eMuqual+pqRm/QN1ZKzgEWSsZ74DZHgRNsyX8/CI0UbCTwtiCazNEbQSVRQfOQOUyMlyJooZdYIZHFJs1PRoQDr+21JWye+I7s+PunLihJrQHfFy7HS9RgNyE2nGjVdYabo5kM7dUMmJ3RIJ6/v0GYW4LRmxbaIEzWfwD5T1d6kYUHV/i55/C853qpnk3vNryKvPyAiap37MeP+n/XmkmozuPnjr9J1plus4EGuxs9vcLJUaWL1zW1hrhO603LB4PFdxDfXErwH7cZoljcUcHcmPb3+VXHMfqdgUnf9A0iG0PK9IOvO2VJzZpz4wpx38lQ+qPG2yXN6Z6w8fuN3YFZiqepMCBbJCY/De7UDPtlsmwMftU2+mU4zUXH+Lro4lrv2QsJx5QCRVkAOqYadMiTX9o4Ff6Qpr0vY=
