mongodb3:
    image: mongo:3.6.0
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
openldap-endpoint:
    image: osixia/openldap:latest
    environment:
        - LDAP_ADMIN_PASSWORD=admin
mongodb-endpoint:
    image: mongo:3.6.0
mariadb-endpoint:
    image: mariadb
    environment:
        - MYSQL_DATABASE=admin
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_USER=admin
moodle-endpoint:
    image: jhardison/moodle:latest
    links:
        - moodle-db
    environment:
        - MOODLE_URL=http://localhost:8080
moodle-db:
    image: mysql:latest
    environment:
        - MYSQL_DATABASE=moodle
        - MYSQL_ROOT_PASSWORD=moodle
        - MYSQL_USER=moodle
balloon:
    image: gyselroth/balloon:2.1.8
    links:
        - mongodb3
    entrypoint: php-fpm
    environment:
        - BALLOON_MONGODB_URI=mongodb://mongodb3:27017
balloon-endpoint:
    image: gyselroth/balloon-web:3.0.5
    ports:
        - "8091:443"
    links:
        - balloon
tubee-dev:
    image: gyselroth/tubee-development:latest
    ports:
        - "8090:443"
    volumes:
        - .:/srv/www/tubee
    links:
        - mongodb3
        - openldap-endpoint
        - balloon-endpoint
    environment:
        - TUBEE_MONGODB_URI=mongodb://mongodb3:27017
