version: 2.1

defaults: &defaults
    docker:
      - image: gyselroth/tubee:php7.2-fpm-circleci

jobs:
  build:
    <<: *defaults

    working_directory: /app
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: make
          command: |
            make VERSION="$CIRCLE_BUILD_NUM"
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor

  release:
    <<: *defaults

    working_directory: /app
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: make
          command: |
#            if [[ "${version:0:1}" == "v" ]]; then version=${version:1}; fi;
#            if [ "$version" == "" ]; then version=$CIRCLE_BUILD_NUM; fi;
            make VERSION="$CIRCLE_TAG"
#            if [ "$CIRCLE_TAG" != "" ]; then docker build -t gyselroth/tubee:$version .; fi
      - save_cache:
         key: composer-v1-{{ checksum "composer.lock" }}
         paths:
           - vendor
      - store_artifacts:
          path: /app/dist
      - run:
          name: release
          command: |
            if [[ "$CIRCLE_TAG" == *"-"* ]]; then export docker_tag=latest-unstable; else export docker_tag=latest; fi;
            version="$CIRCLE_TAG";
            echo $version;
#            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
#            docker tag gyselroth/tubee:$version gyselroth/tubee:$docker_tag
#            docker push gyselroth/tubee:$version
#            docker push gyselroth/tubee:$docker_tag
  #            - ! 'if [ "$CIRCLE_TAG" != "" ]; then curl -s -X POST -H ''Content-Type: application/json''
  #              -H ''Accept: application/json'' -H ''Travis-API-Version: 3'' -H "Authorization:
  #              token $TRAVIS_API_TOKEN" -d ''{"request":{"message":"trigger build", "branch":"master"}}''
  #              "https://api.travis-ci.com/repo/gyselroth%2Ftubee-sdk-typescript-node/requests"; fi'

workflows:
  build-deploy:
    jobs:
#      - build:
#          filters:
#            tags:
#              only: /.*/
      - release:
          filters:
            tags:
              only: /^v.*/
