version: 2.1

defaults: &defaults
  working_directory: /tmp/tubee
  docker:
    - image: gyselroth/tubee:php7.2-fpm-circleci

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: build
          command: |
            if [ -z "${CIRCLE_TAG}"];
            then
              version=$CIRCLE_BUILD_NUM;
            else
              version=$CIRCLE_TAG;
              if [ "${version:0:1}" == "v" ]; then version=${CIRCLE_TAG:1}; fi;
              if [ "${version}" == "" ]; then version=${CIRCLE_BUILD_NUM}; fi;
            fi;

            make VERSION=$version
      - save_cache:
         key: composer-v1-{{ checksum "composer.lock" }}
         paths:
           - vendor
      - store_artifacts:
          path: /tmp/tubee/dist

  deploy:
    <<: *defaults

    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
            - composer-v1-
      - run:
          name: composer update
          command: composer update
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      - run:
          name: deploy
          command: |
            if [ -z "${CIRCLE_TAG}"];
            then
              version=$CIRCLE_BUILD_NUM;
            else
              version=$CIRCLE_TAG;
              if [ "${version:0:1}" == "v" ]; then version=${CIRCLE_TAG:1}; fi;
              if [ "${version}" == "" ]; then version=${CIRCLE_BUILD_NUM}; fi;
            fi;

            if [[ "$version" == *"-"* ]]; then docker_tag=latest-unstable; else docker_tag=latest; fi;

            if [ "$CIRCLE_TAG" != "" ];
            then
              docker build -t gyselroth/tubee:$version .;
              echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
              docker tag gyselroth/tubee:$version gyselroth/tubee:$docker_tag;
              docker push gyselroth/tubee:$version
              docker push gyselroth/tubee:$docker_tag
            fi;

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
